---
apiVersion: v1
kind: Namespace
metadata:
  name: sysbench-generic
spec: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sysbench
  namespace: sysbench-generic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#  storageClassName: {your_storage_class}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-file-generic
  namespace: sysbench-generic
spec:
  template:
    metadata:
      name: sysbench-file-generic
    spec:
      containers:
      - name: sysbench-file-generic
        image: quay.io/vcppds7878/sysbench:bench64
        command: ["sh"]
        args:
          - '-c'
          - '/tmp/file-generic.sh'
        volumeMounts:
        - name: tmp-store
          mountPath: /tmp/data
      volumes:
      - name: tmp-store
        persistentVolumeClaim:
          claimName: pvc-sysbench
          readOnly: false
      restartPolicy: Never
